[package]
name = "stable_mir"
version = "0.1.0-preview"
edition = "2021"

[dependencies]
rustc_data_structures = { path = "../rustc_data_structures" }
scoped-tls = "1.0"
serde = { version = "1.0.125", features = [ "derive" ] }
